image: php:5.6

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install git -yqq
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - docker-php-ext-install pdo_mysql

  - curl -sS https://getcomposer.org/installer | php

  - php composer.phar install

services:
  - mysql

variables:
  MYSQL_DATABASE: blog
  MYSQL_ROOT_PASSWORD: password

test:mysql:
  script:
    - vendor/bin/phpunit --configuration phpunit_mysql.xml --coverage-text

test:php7:mysql:
  image: php:7
  script:
    - vendor/bin/phpunit --configuration phpunit_mysql.xml --coverage-text
  allow_failure: true
