services:
  app:
    build: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY:
      APP_TIMEZONE: UTC

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: blog
      DB_USERNAME: user
      DB_PASSWORD: password

      CACHE_DRIVER: memcached
      QUEUE_DRIVER: sync

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: user
